"""rename uid id

Revision ID: ad4c977a6e72
Revises: c3ffabb26325
Create Date: 2025-03-04 00:48:01.271917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ad4c977a6e72'
down_revision = 'c3ffabb26325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uid', new_column_name='id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id', 'uid')
    # ### end Alembic commands ###
