"""remake NOT NULL, NULL email

Revision ID: c75f6cb88039
Revises: f362f701d1ec
Create Date: 2025-03-04 15:39:31.436774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c75f6cb88039'
down_revision = 'f362f701d1ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', existingh_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
